//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMarksheet
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string TamilMark { get; set; }
        public string EnglishMark { get; set; }
        public string MathsMark { get; set; }
        public string ScienceMark { get; set; }
        public string SocialMark { get; set; }
        public string TotalMark { get; set; }
    }
}
